[tool.poetry]
name = "rate_app"
version = "0.1.0"
description = ""
authors = ["eva.kao <aa8954158@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
black = "^23.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
